name: Test GitHub Secrets

on:
  workflow_dispatch:  # Permite ejecutar manualmente desde GitHub Actions

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar Secret
        run: echo "El secreto es: ${{ secrets.TEST_SECRET }}"

