name: Test GitHub Secrets

on:
  workflow_dispatch:  # Permite ejecutarlo manualmente desde GitHub Actions

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar Secret
        env:
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
        run: echo "El secreto es: $TEST_SECRET"

