name: Test GitHub Secrets

on:
  workflow_dispatch:  # Permite ejecutarlo manualmente desde GitHub Actions

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Mostrar Secret
        run: echo "El secreto es $TEST_SECRET"
        env:
          TEST_SECRET: ${{ secrets.SERVER_IP}}
